import type { Exam } from './records';

export interface ICSProductOptions {
    appName?: string;
    domain?: string;
}

const DEFAULT_PRODUCT: Required<ICSProductOptions> = {
    appName: 'njupt-search',
    domain: 'njupt.hicancan.top'
};

const formatICSDate = (isoString: string): string => {
    const withoutTimezone = isoString.replace(/[+-]\d{2}:\d{2}$|Z$/, '');
    const value = withoutTimezone.replace(/[-:]/g, '').split('.')[0];
    if (!value) throw new Error(`Invalid exam timestamp: ${isoString}`);
    return value;
};

const hashIdentity = (identity: string): string => {
    let hash = 0x811c9dc5;
    for (let index = 0; index < identity.length; index += 1) {
        hash ^= identity.charCodeAt(index);
        hash = Math.imul(hash, 0x01000193);
    }
    return (hash >>> 0).toString(16).padStart(8, '0');
};

export const getExamCalendarIdentity = (exam: Exam): string => (
    `${exam.exam_period_id}\u001f${exam.stable_key}`
);

const escapeICSValue = (value: string): string => value
    .replace(/\\/g, '\\\\')
    .replace(/,/g, '\\,')
    .replace(/;/g, '\\;')
    .replace(/\r\n/g, '\\n')
    .replace(/\r/g, '\\n')
    .replace(/\n/g, '\\n');

const foldLine = (line: string): string => {
    const encoder = new TextEncoder();
    if (encoder.encode(line).length <= 75) return line;
    const result: string[] = [];
    let current = '';
    let bytes = 0;
    for (const character of line) {
        const characterBytes = encoder.encode(character).length;
        const limit = result.length === 0 ? 75 : 74;
        if (bytes + characterBytes > limit) {
            result.push(current);
            current = character;
            bytes = characterBytes;
        } else {
            current += character;
            bytes += characterBytes;
        }
    }
    if (current) result.push(current);
    return result.join('\r\n ');
};

export const generateICSContent = (
    exams: Exam[],
    className: string,
    reminders: number[],
    product: ICSProductOptions = {}
): string => {
    if (exams.length === 0) {
        throw new Error('无法生成日历：未提供有效的考试数据');
    }
    const { appName, domain } = { ...DEFAULT_PRODUCT, ...product };
    const now = `${new Date().toISOString().replace(/[-:]/g, '').split('.')[0]}Z`;
    const lines = [
        'BEGIN:VCALENDAR',
        'VERSION:2.0',
        `PRODID:-//${domain}//${appName}//CN`,
        `X-WR-CALNAME:南邮考试-${className}`,
        'CALSCALE:GREGORIAN',
        'METHOD:PUBLISH',
        'BEGIN:VTIMEZONE',
        'TZID:Asia/Shanghai',
        'X-LIC-LOCATION:Asia/Shanghai',
        'BEGIN:STANDARD',
        'TZOFFSETFROM:+0800',
        'TZOFFSETTO:+0800',
        'TZNAME:CST',
        'DTSTART:19700101T000000',
        'END:STANDARD',
        'END:VTIMEZONE'
    ];

    for (const exam of exams) {
        const description = [
            `课程代码: ${exam.course_code}`,
            `教师: ${exam.teacher}`,
            `班级: ${exam.class_name}`,
            `人数: ${exam.count}`,
            exam.notes ? `备注: ${exam.notes}` : '',
            '',
            `Generated by ${appName}.${domain}`
        ].filter(Boolean).join('\n');
        lines.push(
            'BEGIN:VEVENT',
            `UID:exam-${hashIdentity(getExamCalendarIdentity(exam))}@${domain}`,
            `DTSTAMP:${now}`,
            `DTSTART;TZID=Asia/Shanghai:${formatICSDate(exam.start_timestamp)}`,
            `DTEND;TZID=Asia/Shanghai:${formatICSDate(exam.end_timestamp)}`,
            `SUMMARY:${escapeICSValue(`考试: ${exam.course_name}`)}`,
            `LOCATION:${escapeICSValue(`[${exam.campus}] ${exam.location}`)}`,
            `DESCRIPTION:${escapeICSValue(description)}`,
            'STATUS:CONFIRMED'
        );
        for (const minutes of reminders) {
            lines.push(
                'BEGIN:VALARM',
                'ACTION:DISPLAY',
                'DESCRIPTION:考试提醒',
                `TRIGGER:-PT${minutes}M`,
                'END:VALARM'
            );
        }
        lines.push('END:VEVENT');
    }
    lines.push('END:VCALENDAR');
    return lines.map(foldLine).join('\r\n');
};
