// 辅助函数：安全地格式化 ICS 时间 (UTC -> Local String for ICS with TZID)
const formatICSDate = (isoString) => {
    if (!isoString) return null;
    // 移除毫秒、破折号和冒号，保留 YYYYMMDDTHHMMSS 格式
    return isoString.replace(/[-:]/g, '').split('.')[0];
};

const foldLine = (line) => {
    if (line.length <= 75) return line;
    let folded = line.substring(0, 75);
    let remainder = line.substring(75);
    while (remainder.length > 0) {
        folded += '\r\n ' + remainder.substring(0, 74);
        remainder = remainder.substring(74);
    }
    return folded;
};

// 核心修复：增加 Timezone 支持
export const generateICSContent = (exams, className, reminders) => {
    const now = new Date().toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';

    let lines = [
        'BEGIN:VCALENDAR',
        'VERSION:2.0',
        'PRODID:-//hicancan//NJUPT Exam Sync//CN',
        'X-WR-CALNAME:南邮考试-' + className,
        'CALSCALE:GREGORIAN',
        'METHOD:PUBLISH'
    ];

    exams.forEach((exam, index) => {
        if (!exam.start_timestamp || !exam.end_timestamp) return;

        const start = formatICSDate(exam.start_timestamp);
        const end = formatICSDate(exam.end_timestamp);

        const descText = [
            `课程代码: ${exam.course_code || '-'}`,
            `教师: ${exam.teacher || '未知'}`,
            `班级: ${exam.class_name}`,
            `人数: ${exam.count}`,
            exam.notes ? `备注: ${exam.notes}` : '',
            '',
            'Generated by njupt.hicancan.top'
        ].filter(Boolean).join('\\n');

        const location = `${exam.campus ? `[${exam.campus}] ` : ''}${exam.location}`;

        lines.push('BEGIN:VEVENT');
        lines.push(`UID:${exam.id}-${index}@hicancan.top`);
        lines.push(`DTSTAMP:${now}`);
        // 修复：强制指定亚洲/上海时区，避免浮动时间问题
        lines.push(`DTSTART;TZID=Asia/Shanghai:${start}`);
        lines.push(`DTEND;TZID=Asia/Shanghai:${end}`);
        lines.push(`SUMMARY:考试: ${exam.course}`);
        lines.push(`LOCATION:${location}`);
        lines.push(`DESCRIPTION:${descText}`);
        lines.push('STATUS:CONFIRMED');

        reminders.forEach(min => {
            lines.push('BEGIN:VALARM');
            lines.push('ACTION:DISPLAY');
            lines.push('DESCRIPTION:Exam Reminder');
            lines.push(`TRIGGER:-PT${min}M`);
            lines.push('END:VALARM');
        });

        lines.push('END:VEVENT');
    });

    lines.push('END:VCALENDAR');
    return lines.map(foldLine).join('\r\n');
};
