import { Exam } from '../types';
import { APP_CONFIG } from '../constants';

/**
 * 格式化 ISO 时间字符串为 ICS 本地时间格式
 * RFC 5545: 使用 TZID 时，时间值必须是本地时间格式，不含 UTC 偏移量
 * 输入: "2025-11-18T13:30:00+08:00"
 * 输出: "20251118T133000"
 */
const formatICSDate = (isoString?: string): string | null => {
    if (!isoString) return null;
    // 先移除时区偏移量 (+08:00 或 Z)，然后移除破折号和冒号
    const withoutTz = isoString.replace(/[+-]\d{2}:\d{2}$|Z$/, '');
    const cleaned = withoutTz.replace(/[-:]/g, '').split('.')[0];
    return cleaned ?? null;
};

/**
 * 生成 ASCII 安全的 UID
 * RFC 5545 建议 UID 使用 ASCII 字符以确保兼容性
 */
const generateUID = (examId: string, index: number): string => {
    // 将中文文件名转换为 hash
    let hash = 0;
    for (let i = 0; i < examId.length; i++) {
        const char = examId.charCodeAt(i);
        hash = ((hash << 5) - hash) + char;
        hash = hash & hash; // Convert to 32bit integer
    }
    const hashStr = Math.abs(hash).toString(36);
    return `exam-${hashStr}-${index}@${APP_CONFIG.DOMAIN}`;
};

// RFC 5545 标准要求转义特殊字符
const escapeICSValue = (str: string): string => {
    return str
        .replace(/\\/g, '\\\\')  // 反斜杠必须首先转义
        .replace(/,/g, '\\,')
        .replace(/;/g, '\\;')
        .replace(/\r\n/g, '\\n')
        .replace(/\r/g, '\\n')
        .replace(/\n/g, '\\n');
};

/**
 * RFC 5545 行折叠：每行最多 75 字节
 * 注意：必须在 UTF-8 字符边界处折叠，不能截断多字节字符
 */
const foldLine = (line: string): string => {
    const encoder = new TextEncoder();
    const bytes = encoder.encode(line);

    if (bytes.length <= 75) return line;

    const result: string[] = [];
    let currentLine = '';
    let currentBytes = 0;
    const maxBytes = 75;
    const continuationMaxBytes = 74; // 续行前有一个空格占用 1 字节

    for (const char of line) {
        const charBytes = encoder.encode(char).length;
        const limit = result.length === 0 ? maxBytes : continuationMaxBytes;

        if (currentBytes + charBytes > limit) {
            result.push(currentLine);
            currentLine = char;
            currentBytes = charBytes;
        } else {
            currentLine += char;
            currentBytes += charBytes;
        }
    }

    if (currentLine) {
        result.push(currentLine);
    }

    return result.join('\r\n ');
};

// 核心修复：增加 Timezone 支持
export const generateICSContent = (exams: Exam[], className: string, reminders: number[]): string => {
    if (!exams || exams.length === 0) {
        throw new Error('无法生成日历：未提供有效的考试数据');
    }
    const now = new Date().toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';

    const lines = [
        'BEGIN:VCALENDAR',
        'VERSION:2.0',
        'PRODID:-//' + APP_CONFIG.DOMAIN + '//' + APP_CONFIG.APP_NAME + '//CN',
        'X-WR-CALNAME:南邮考试-' + className,
        'CALSCALE:GREGORIAN',
        'METHOD:PUBLISH',
        // VTIMEZONE for Asia/Shanghai (China Standard Time, UTC+8, no DST)
        'BEGIN:VTIMEZONE',
        'TZID:Asia/Shanghai',
        'X-LIC-LOCATION:Asia/Shanghai',
        'BEGIN:STANDARD',
        'TZOFFSETFROM:+0800',
        'TZOFFSETTO:+0800',
        'TZNAME:CST',
        'DTSTART:19700101T000000',
        'END:STANDARD',
        'END:VTIMEZONE'
    ];

    exams.forEach((exam, index) => {
        if (!exam.start_timestamp || !exam.end_timestamp) return;

        const start = formatICSDate(exam.start_timestamp);
        const end = formatICSDate(exam.end_timestamp);

        const descText = [
            `课程代码: ${exam.course_code || '-'}`,
            `教师: ${exam.teacher || '未知'}`,
            `班级: ${exam.class_name}`,
            `人数: ${exam.count}`,
            exam.notes ? `备注: ${exam.notes}` : '',
            '',
            `Generated by njupt.${APP_CONFIG.DOMAIN}`
        ].filter(Boolean).join('\n');

        const location = `${exam.campus ? `[${exam.campus}] ` : ''}${exam.location}`;
        const summary = exam.course_name;

        lines.push('BEGIN:VEVENT');
        lines.push(`UID:${generateUID(exam.id, index)}`);
        lines.push(`DTSTAMP:${now}`);
        // 修复：强制指定亚洲/上海时区，避免浮动时间问题
        lines.push(`DTSTART;TZID=Asia/Shanghai:${start}`);
        lines.push(`DTEND;TZID=Asia/Shanghai:${end}`);
        lines.push(`SUMMARY:${escapeICSValue('考试: ' + summary)}`);
        lines.push(`LOCATION:${escapeICSValue(location)}`);
        lines.push(`DESCRIPTION:${escapeICSValue(descText)}`);
        lines.push('STATUS:CONFIRMED');

        reminders.forEach(min => {
            lines.push('BEGIN:VALARM');
            lines.push('ACTION:DISPLAY');
            lines.push('DESCRIPTION:Exam Reminder');
            lines.push(`TRIGGER:-PT${min}M`);
            lines.push('END:VALARM');
        });

        lines.push('END:VEVENT');
    });

    lines.push('END:VCALENDAR');
    return lines.map(foldLine).join('\r\n');
};
