import { Exam } from '../types';
import { APP_CONFIG } from '../constants';

// 辅助函数：安全地格式化 ICS 时间 (UTC -> Local String for ICS with TZID)
const formatICSDate = (isoString?: string): string | null => {
    if (!isoString) return null;
    // 移除毫秒、破折号和冒号，保留 YYYYMMDDTHHMMSS 格式
    const parts = isoString.replace(/[-:]/g, '').split('.');
    return parts[0] ?? null;
};

// RFC 5545 标准要求转义特殊字符
const escapeICSValue = (str: string): string => {
    return str
        .replace(/\\/g, '\\\\')  // 反斜杠必须首先转义
        .replace(/,/g, '\\,')
        .replace(/;/g, '\\;')
        .replace(/\n/g, '\\n');
};

const foldLine = (line: string): string => {
    if (line.length <= 75) return line;
    let folded = line.substring(0, 75);
    let remainder = line.substring(75);
    while (remainder.length > 0) {
        folded += '\r\n ' + remainder.substring(0, 74);
        remainder = remainder.substring(74);
    }
    return folded;
};

// 核心修复：增加 Timezone 支持
export const generateICSContent = (exams: Exam[], className: string, reminders: number[]): string => {
    if (!exams || exams.length === 0) {
        throw new Error('无法生成日历：未提供有效的考试数据');
    }
    const now = new Date().toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';

    const lines = [
        'BEGIN:VCALENDAR',
        'VERSION:2.0',
        'PRODID:-//' + APP_CONFIG.DOMAIN + '//' + APP_CONFIG.APP_NAME + '//CN',
        'X-WR-CALNAME:南邮考试-' + className,
        'CALSCALE:GREGORIAN',
        'METHOD:PUBLISH',
        // VTIMEZONE for Asia/Shanghai (China Standard Time, UTC+8, no DST)
        'BEGIN:VTIMEZONE',
        'TZID:Asia/Shanghai',
        'X-LIC-LOCATION:Asia/Shanghai',
        'BEGIN:STANDARD',
        'TZOFFSETFROM:+0800',
        'TZOFFSETTO:+0800',
        'TZNAME:CST',
        'DTSTART:19700101T000000',
        'END:STANDARD',
        'END:VTIMEZONE'
    ];

    exams.forEach((exam, index) => {
        if (!exam.start_timestamp || !exam.end_timestamp) return;

        const start = formatICSDate(exam.start_timestamp);
        const end = formatICSDate(exam.end_timestamp);

        const descText = [
            `课程代码: ${exam.course_code || '-'}`,
            `教师: ${exam.teacher || '未知'}`,
            `班级: ${exam.class_name}`,
            `人数: ${exam.count}`,
            exam.notes ? `备注: ${exam.notes}` : '',
            '',
            `Generated by njupt.${APP_CONFIG.DOMAIN}`
        ].filter(Boolean).join('\n');

        const location = `${exam.campus ? `[${exam.campus}] ` : ''}${exam.location}`;
        const summary = exam.course_name;

        lines.push('BEGIN:VEVENT');
        lines.push(`UID:${exam.id}-${index}@${APP_CONFIG.DOMAIN}`);
        lines.push(`DTSTAMP:${now}`);
        // 修复：强制指定亚洲/上海时区，避免浮动时间问题
        lines.push(`DTSTART;TZID=Asia/Shanghai:${start}`);
        lines.push(`DTEND;TZID=Asia/Shanghai:${end}`);
        lines.push(`SUMMARY:${escapeICSValue('考试: ' + summary)}`);
        lines.push(`LOCATION:${escapeICSValue(location)}`);
        lines.push(`DESCRIPTION:${escapeICSValue(descText)}`);
        lines.push('STATUS:CONFIRMED');

        reminders.forEach(min => {
            lines.push('BEGIN:VALARM');
            lines.push('ACTION:DISPLAY');
            lines.push('DESCRIPTION:Exam Reminder');
            lines.push(`TRIGGER:-PT${min}M`);
            lines.push('END:VALARM');
        });

        lines.push('END:VEVENT');
    });

    lines.push('END:VCALENDAR');
    return lines.map(foldLine).join('\r\n');
};
